config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # , controllers: {
    # sessions: 'users/sessions',
    # registrations: 'users/registrations'
  # }

  # ここにルートパス設定
  root 'home#home'
  get  "home/about"  => "home#index"
  resources :books, only: [:index, :create, :show, :destroy, :update, :edit]
  resources :users, only: [:index, :create, :show, :update, :edit ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
    validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: {in: 2..20 }
  validates :introduction, uniqueness: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action  :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password) }

    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]


  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user_id
    redirect_to books_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]


  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
    
    def correct_user
      user = User.find(params[:id])
      if current_user != user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <h2>User info</h2>
    <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, class: "profile-thumb", fallback: "no_image.jpg"%>
  <table class="table">
    <tbody>
      <tr>
    	  <th>name</th>
    	  <th><%= current_user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>


<div class="row">
  <!--<a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_24462" href="/users/24462/edit"></a>-->
  <%= link_to "",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>

  <h2>New book</h2>
  <%= form_with(model: book, local: true) do |f| %>
    <div class="row">
      <div class="field row">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "col-xs-12 book_title"%>
      </div>
      <div class="field row">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "col-xs-12 book_body"%>
      </div>
      <div class="field row">
        <%= f.submit "Create Book", class: "btn btn-primary col-xs-12"%>
      </div>
    </div>
  <% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul class="error-message">
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>
    <%= form_with(model: @book, local: true) do |f| %>
      <div class="field row">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "col-xs-12 book_title"%>
      </div>
      <div class="field row">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "col-xs-12 book_body"%>
      </div>
      <div class="field row">
        <%= f.submit "Update Book", class: "btn btn-primary col-xs-12"%>
      </div>
    <% end %>
    <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul class="error-message">
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="container">
  <div class="row">

    <div class="col-xs-3">
      <%= render 'books/list', book: @book, user: current_user %>
    </div>

    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, class: "profile-thumb", fallback: "no_image.jpg", size:'40x40'%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <div class="row">

    <div class="col-xs-3">
      <%= render 'books/list', book: @book_new %>
    </div>



    <div class="col-xs-9">
    	<table class="table">
    		<h2>Book detail</h2>
    		<thead> 
    		  <tr>
    		    <th>
    		      
    		    </th>
    		    <th>
    		      Title
    		    </th>
    		    <th>
    		      Opinion
    		    </th>
    		  </tr>
    		</thead>
    		    <tr>
              <th>
                <!--<a href="/users/24506">-->
                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, class: "profile-thumb", fallback: "no_image.jpg", size:'40x40'%> 
                <%= link_to @user.name , user_path(@user.id) %>
                  <!--</a>-->
              </th>
            <td><%= @book.title %></td>
            
            <td><%= @book.body %></td>
            
              <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn-sm btn-danger" %></td>
              <!--<td><a data-confirm="本当に消しますか？" class="btn-sm btn-danger destroy_book_38309" rel="nofollow" data-method="delete" href="/books/38309">Destroy</a></td>-->
              <% end %>
          </tr>
        </table>
    </div>
  </div>
</div>

app/views/home/home.html.erb
<div class="container">
  <div class="row">
    <% if flash[:notice] %>
    <div class="flash">
    <%= flash[:notice] %>
    </div>
    <% end %>
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>
    <div class="btn-wrapper">
      <div class="row">
         <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>
  </div>
  </div>


  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <p id="notice"></p>
  <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<!--ヘッダー部分-->
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <!--<li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>-->
          <li><%= link_to " Home", user_path(current_user), class: "glyphicon glyphicon-home home"%></li>
          <li><a class="glyphicon glyphicon-user users" href="/users"> Users</a></li>
          <li><a class="glyphicon glyphicon-book books" href="/books"> Books</a></li>
          <li><a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
        <% else %>
          <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
          <li><a class="glyphicon glyphicon-link about" href="/home/about"> About</a></li>
          <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a></li>
          <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>




<body>
  <div class="container">
    <%= yield %>
  </div>
</body>


<!--フッター部分-->
<footer>
  <div class="container">
  	<div class="row">
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

</html>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
  <div class="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul class="error-message">
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <h2>User info</h2>
  <%= form_with model:@user, local:true do |f| %>
    <div class="field row">
      <label for="user_name">Name</label>
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="field row">
      <label for="image">Image</label>
       <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    </div>
    <div class="field row">
      <label for="introduction">Introduction</label>
      <%= f.text_area :introduction, autofocus: true %>
    </div>
  <%= f.submit "Update User" , class: "btn-default" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'books/list', book: @book, user: current_user%>
    </div>
    <div class="col-xs-9">
      <h2>Users</h2>

      <table class="table">
        <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, class: "profile-thumb", fallback: "no_image.jpg", size:'40x40'%></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
        <%= render 'books/list', book: @book, user: current_user %>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
         <% @books.each do |book| %>
              <tr>
                <td>
                  <!--<a href="/users/24431">-->
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, class: "profile-thumb", fallback: "no_image.jpg", size:'40x40'%> 

                </td>
                <td class="content"><%= link_to book.title, book, class: "book_#[book.id]" %></td>
                <td><%= book.body %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>